import 'package:freezed_annotation/freezed_annotation.dart';

part 'assistant_answer.freezed.dart';

/// How an answer was produced.
///
/// Surfaced in the UI because the two modes carry different trust: retrieval
/// quotes the user's own documents, whereas a generated answer is the model's
/// paraphrase and can be wrong in ways an extract cannot.
enum AnswerSource {
  /// Extracted verbatim from indexed page text. Always available — this is the
  /// engine the assistant is built on.
  retrieval,

  /// Generated by the optional on-device model, when the user has enabled it.
  onDeviceModel,
}

/// A passage the answer was drawn from, so the user can check it.
///
/// Every retrieval answer carries at least one of these. An answer with no
/// citation is the assistant admitting it found nothing — which is the honest
/// outcome for a question the documents do not cover.
@freezed
abstract class AnswerCitation with _$AnswerCitation {
  const AnswerCitation._();

  const factory AnswerCitation({
    required String documentId,

    /// Denormalised so the citation chip renders without a repository read.
    /// A rename leaves this stale until the next answer, which is acceptable
    /// for a transcript — it records what the document was called at the time.
    required String documentTitle,
    required int pageIndex,
    required String snippet,
  }) = _AnswerCitation;

  String get pageLabel => 'Page ${pageIndex + 1}';
}

/// The assistant's reply to one question.
@freezed
abstract class AssistantAnswer with _$AssistantAnswer {
  const AssistantAnswer._();

  const factory AssistantAnswer({
    required String text,
    @Default(<AnswerCitation>[]) List<AnswerCitation> citations,
    @Default(AnswerSource.retrieval) AnswerSource source,
  }) = _AssistantAnswer;

  /// Whether the answer is backed by something the user can go and read.
  /// The UI uses this to decide whether to show the "not found in your
  /// documents" treatment.
  bool get isGrounded => citations.isNotEmpty;

  /// Distinct documents the answer drew on, in citation order.
  List<String> get citedDocumentIds {
    final seen = <String>{};
    return citations
        .map((citation) => citation.documentId)
        .where(seen.add)
        .toList(growable: false);
  }
}
