import 'package:freezed_annotation/freezed_annotation.dart';

part 'assistant_answer.freezed.dart';

/// How an answer was produced.
///
/// Surfaced in the UI because the two modes carry different trust: retrieval
/// quotes the user's own documents, whereas a generated answer is the model's
/// paraphrase and can be wrong in ways an extract cannot.
enum AnswerSource {
  /// Extracted verbatim from indexed page text. Always available — this is the
  /// engine the assistant is built on.
  retrieval,

  /// Generated by the optional on-device model, when the user has enabled it.
  onDeviceModel,
}

/// Why the assistant replied the way it did.
///
/// An enum rather than the UI matching on message strings. Every unhelpful
/// outcome has a different cause and a different thing the user can do about
/// it, and telling them apart in the domain is what lets the screen say
/// something useful instead of one generic apology.
enum AnswerKind {
  /// Quoted from the user's documents.
  grounded,

  /// The document's own sentences, chosen to represent the whole of it.
  ///
  /// Grounded in exactly the same sense — every line is lifted from a page —
  /// but it answers no question, so there is no coverage to be confident about.
  summary,

  /// Every value of one shape found in the document: the dates, the amounts,
  /// the names.
  extraction,

  /// A summary or a listing was asked for without saying what of.
  ///
  /// Distinct from [unclearQuestion]: the request was perfectly clear, it just
  /// arrived with no document attached, and the fix is to open one rather than
  /// to rephrase.
  needsDocument,

  /// Documents were searched and none contained the answer.
  noMatch,

  /// Documents exist, but none has had its text recognised yet.
  noRecognisedText,

  /// There is nothing in the library to search.
  emptyLibrary,

  /// The question carried no term worth searching for.
  unclearQuestion,
}

/// How well the quoted passage actually answered the question.
///
/// A *retrieval* confidence, not a claim about truth. It reports how completely
/// the passage covered the question's terms — never whether the document is
/// correct. The UI labels these "Strong/Partial/Weak match" for that reason:
/// "confident" would be a promise the engine is in no position to make.
enum AnswerConfidence { strong, partial, weak }

/// A passage the answer was drawn from, so the user can check it.
///
/// Every retrieval answer carries at least one of these. An answer with no
/// citation is the assistant admitting it found nothing — which is the honest
/// outcome for a question the documents do not cover.
@freezed
abstract class AnswerCitation with _$AnswerCitation {
  const AnswerCitation._();

  const factory AnswerCitation({
    required String documentId,

    /// Denormalised so the citation chip renders without a repository read.
    /// A rename leaves this stale until the next answer, which is acceptable
    /// for a transcript — it records what the document was called at the time.
    required String documentTitle,
    required int pageIndex,
    required String snippet,

    /// Question terms this passage actually contained, so the citation can
    /// show *why* it was cited rather than only where it came from.
    @Default(<String>[]) List<String> matchedTerms,

    /// Score relative to the best passage in the same answer, 0–1. Comparable
    /// within one answer only, exactly like the BM25 scores beneath it.
    @Default(0.0) double relevance,
  }) = _AnswerCitation;

  String get pageLabel => 'Page ${pageIndex + 1}';
}

/// The assistant's reply to one question.
@freezed
abstract class AssistantAnswer with _$AssistantAnswer {
  const AssistantAnswer._();

  const factory AssistantAnswer({
    required String text,
    @Default(<AnswerCitation>[]) List<AnswerCitation> citations,
    @Default(AnswerSource.retrieval) AnswerSource source,
    @Default(AnswerKind.grounded) AnswerKind kind,

    /// Set only when a question was answered — [AnswerKind.grounded], or
    /// [AnswerKind.extraction] where the shape found stands in for coverage.
    ///
    /// Null everywhere else. Nothing was found to be confident about, and a
    /// summary answers no question, so there is no coverage to report.
    AnswerConfidence? confidence,

    /// How many documents were read to produce this. Shown so an answer drawn
    /// from one document out of forty does not look like the whole library
    /// agreed with it.
    @Default(0) int documentsSearched,
  }) = _AssistantAnswer;

  /// Whether the answer is backed by something the user can go and read.
  bool get isGrounded => citations.isNotEmpty;

  /// Distinct documents the answer drew on, in citation order.
  List<String> get citedDocumentIds {
    final seen = <String>{};
    return citations
        .map((citation) => citation.documentId)
        .where(seen.add)
        .toList(growable: false);
  }

  /// Citations grouped by document, preserving both document and page order.
  ///
  /// An answer that draws two pages from the same contract should read as one
  /// source with two references, not as two unrelated sources.
  Map<String, List<AnswerCitation>> get citationsByDocument {
    final grouped = <String, List<AnswerCitation>>{};
    for (final citation in citations) {
      grouped
          .putIfAbsent(citation.documentId, () => <AnswerCitation>[])
          .add(citation);
    }
    return grouped;
  }

  bool get spansMultipleDocuments => citedDocumentIds.length > 1;
}
