import 'package:hive_ce_flutter/hive_ce_flutter.dart';

import '../../../hive_registrar.g.dart';
import '../constants/hive_boxes.dart';

/// Owns Hive's one-time startup sequence.
///
/// Called from `bootstrap()` before `runApp`, so that every provider can assume
/// its box is already open and read synchronously — no `AsyncValue` loading
/// state just to reach local preferences.
///
/// Note this project uses **hive_ce** (Community Edition), not the original
/// `hive` package: upstream Hive is unmaintained and its code generator no
/// longer works on modern Dart SDKs.
abstract final class HiveInitializer {
  /// Initialises Hive, registers every adapter, and opens the settings box.
  ///
  /// Only [HiveBoxes.settings] is opened here — it is the one box needed before
  /// the first frame regardless of which screen the app lands on. Feature boxes
  /// are opened by their own feature (see `openDocumentsBox`) and injected the
  /// same way, so a box is never opened by a feature that does not use it.
  ///
  /// The index and chat boxes arrive in Phases 6 and 7.
  static Future<Box<dynamic>> init() async {
    await Hive.initFlutter();

    // Generated by hive_ce_generator into `lib/hive_registrar.g.dart` from
    // every `@HiveType` in the project. Adapters must be registered before any
    // box holding them is opened, and their type ids come from [HiveTypeIds]
    // so two models can never collide.
    Hive.registerAdapters();

    return Hive.openBox<dynamic>(HiveBoxes.settings);
  }

  /// Flushes and closes all open boxes. Used by tests and by any future
  /// "clear all data" action in settings.
  static Future<void> close() => Hive.close();
}
